### PR TITLE
Prefer the last modification time of the cache objects

### PR DESCRIPTION
**Pull request by wagdav**
The cache objects can be newly created or updated.  When the cache
object is updated by a build, it makes more sense to use the last
modification as an 'update time' instead of the creation time.

This patch factors out a `getCreateTime` function which tries to
retrieve the last modification time and the object creation time, in
this order.

### CODE REVIEW

**Comment by lehins** [comment]
Thank you attempt to contribute, but unfortunately I have to close this PR.
Current behavior is actually intended to work this way and is required for proper cache expiration.  That is the reason why it is called `creationTime`, rather than `lastUpdateTime`. I guess I could document it a bit better in the code. 

If you look at `cache-s3 restore --help` you'll see:
```
  --max-age ARG            Amount of time cache will be valid for from the
                           moment it was initially uploaded to S3, i.e. updating
                           cache doesn't reset the time counter. Accepts common
                           variations of (year|day|hour|min|sec), , eg.
                           --max-age='30 days 1 hour' or --max-age='1h 45m'
```

This feature is very useful for occasional stack lts updates. `--max-age` will cause the cache to be occasionally invalidated and rebuilt from scratch, thus preventing infinite accumulation of files that are no longer used. If we would switch to prefer the `gorsLastModified` it would be possible for cache never to get cleared.

**Comment by lehins** [comment]
@wagdav I do like the refactoring part of this PR though, so if you switch back to:
```haskell
  (HM.lookup metaCreateTimeKey (resp ^. gorsMetadata) >>= parseISO8601) <|>
  (resp ^. gorsLastModified)
````
I'll gladly reopen the PR and merge it in.

**Comment by wagdav** [comment]
Ah, thanks for the explanation!

My initial motivation for this PR was the following message:
```
[cache-s3][Info ][Tue, 16 Apr 2019 09:34:01 UTC]: <master.cache> - Restoring cache from Tue, 16 Apr 2019 06:17:03 UTC with total size: 309.9 MiB
```
Here we see the creation time of the object. This is confusing when a previous build already updated the cache, so we actually using a cache that is newer (which is described by the last modification time).

**Comment by wagdav** [comment]
> @wagdav I do like the refactoring part of this PR though, so if you switch back to:
> 
> ```haskell
>   (HM.lookup metaCreateTimeKey (resp ^. gorsMetadata) >>= parseISO8601) <|>
>   (resp ^. gorsLastModified)
> ```
> 
> I'll gladly reopen the PR and merge it in.

I'll open a new PR with the refactoring, so it's better documented.

**Pull request closed without merging**
